In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import plotly
import plotly.express as px
import plotly.graph_objects as go
plt.rcParams['figure.figsize'] = 15,6
import cufflinks as cf
import plotly.offline as pyo
from plotly.offline import init_notebook_mode, plot, iplot

In [2]:
data = pd.read_csv(r'C:\Users\HP\Downloads\HR_comma_sep.csv')

In [3]:
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [5]:
data["Department"].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [6]:
for col in data.columns:
    data.loc[data["Department"] == "sales" , "Department"] = 1
    data.loc[data["Department"] == "accounting" , "Department"] = 2
    data.loc[data["Department"] == "hr" , "Department"] = 3
    data.loc[data["Department"] == "technical" , "Department"] = 4
    data.loc[data["Department"] == "support" , "Department"] = 5
    data.loc[data["Department"] == "management" , "Department"] = 6
    data.loc[data["Department"] == "IT" , "Department"] = 7
    data.loc[data["Department"] == "product_mng" , "Department"] = 8
    data.loc[data["Department"] == "marketing" , "Department"] = 9
    data.loc[data["Department"] == "RandD" , "Department"] = 0
    


C:\Users\HP\Anaconda3\lib\site-packages\pandas\core\ops.py:1649: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison



In [7]:
data["salary"].unique()

array(['low', 'medium', 'high'], dtype=object)

In [8]:
for col in data.columns:
    data.loc[data["salary"]=="high","salary"]=1
    data.loc[data["salary"]=="low","salary"]=0
    data.loc[data["salary"]=="medium","salary"]=2

In [9]:
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  Department  \
0                   3              0     1                      0           1   
1                   6              0     1                      0           1   
2                   4              0     1                      0           1   
3                   5              0     1                      0           1   
4                   3              0     1                      0           1   

   salary  
0       0  
1       2  
2       2  
3       0  
4       0

In [10]:
corr_matrix = data.corr().round(2)
corr_matrix

satisfaction_level  last_evaluation  number_project  \
satisfaction_level                   1.00             0.11           -0.14   
last_evaluation                      0.11             1.00            0.35   
number_project                      -0.14             0.35            1.00   
average_montly_hours                -0.02             0.34            0.42   
time_spend_company                  -0.10             0.13            0.20   
Work_accident                        0.06            -0.01           -0.00   
left                                -0.39             0.01            0.02   
promotion_last_5years                0.03            -0.01           -0.01   
Department                           0.01             0.02           -0.00   
salary                               0.04             0.00            0.01   

                       average_montly_hours  time_spend_company  \
satisfaction_level                    -0.02               -0.10   
last_evaluation                        0.34                0.13   
number_project                         0.42                0.20   
average_montly_hours                   1.00                0.13   
time_spend_company                     0.13                1.00   
Work_accident                         -0.01                0.00   
left                                   0.07                0.14   
promotion_last_5years                 -0.00                0.07   
Department                            -0.00                0.02   
salary                                 0.00                0.03   

                       Work_accident  left  promotion_last_5years  Department  \
satisfaction_level              0.06 -0.39                   0.03        0.01   
last_evaluation                -0.01  0.01                  -0.01        0.02   
number_project                 -0.00  0.02                  -0.01       -0.00   
average_montly_hours           -0.01  0.07                  -0.00       -0.00   
time_spend_company              0.00  0.14                   0.07        0.02   
Work_accident                   1.00 -0.15                   0.04        0.01   
left                           -0.15  1.00                  -0.06       -0.01   
promotion_last_5years           0.04 -0.06                   1.00       -0.00   
Department                      0.01 -0.01                  -0.00        1.00   
salary                          0.00 -0.11                   0.06        0.00   

                       salary  
satisfaction_level       0.04  
last_evaluation          0.00  
number_project           0.01  
average_montly_hours     0.00  
time_spend_company       0.03  
Work_accident            0.00  
left                    -0.11  
promotion_last_5years    0.06  
Department               0.00  
salary                   1.00

In [11]:
data.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Department', 'salary'],
      dtype='object')

In [13]:
x= data[["satisfaction_level", "last_evaluation", "number_project","average_montly_hours", "time_spend_company", 
        "Work_accident","promotion_last_5years", "Department", "salary"]]
print(x.shape)

(14999, 9)


In [14]:
y=data["left"]
y.shape

(14999,)

In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors= 5)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 1, stratify = y)

In [17]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [18]:
pred = knn.predict(x_test)

In [19]:
pred

array([0, 1, 0, ..., 0, 1, 1], dtype=int64)

In [20]:
y_pred_prob = knn.predict_proba(x_test)
y_pred_prob[10:12]

array([[1., 0.],
       [1., 0.]])

In [21]:
knn.score(x_test,y_test)

0.9217777777777778

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[3202,  227],
       [ 125,  946]], dtype=int64)

In [23]:
from sklearn.model_selection import cross_val_score

## CREATE A NEW KNN model
knn_cv=KNeighborsClassifier(n_neighbors=3)

In [24]:
### Train model with 5-fold cv

In [25]:
cv_scores=cross_val_score(knn_cv,x,y,cv=5)

In [26]:
print(cv_scores)

[0.94035322 0.913      0.91866667 0.95065022 0.92364121]


In [27]:
cv_scores.mean()

0.929262262547659

In [28]:
from sklearn.model_selection import GridSearchCV

### Another  KNN model
knn2 = KNeighborsClassifier()

### CREATING DICTIONARY OF ALL VALUES WE WANT TO TEST FOR N_NEIGHBORS

param_grid={"n_neighbors": np.arange(2,10)}

### USE GRIDSEARCH TO TEST ALL VALUES FOR N_NEIGHBORS

knn_gscv = GridSearchCV(knn2,param_grid,cv=5)

### FIT MODEL TO DATA

knn_gscv.fit(x,y)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=None,
             param_grid={'n_neighbors': array([2, 3, 4, 5, 6, 7, 8, 9])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [29]:
knn_gscv.best_params_

{'n_neighbors': 2}

In [30]:
knn_gscv.best_score_

0.9458630575371691

In [31]:
knn_final = KNeighborsClassifier(n_neighbors = knn_gscv.best_params_["n_neighbors"])
knn_final.fit(x,y)
y_pred= knn_final.predict(x)
knn_final.score(x,y)

0.9897326488432562

In [32]:
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  Department  \
0                   3              0     1                      0           1   
1                   6              0     1                      0           1   
2                   4              0     1                      0           1   
3                   5              0     1                      0           1   
4                   3              0     1                      0           1   

   salary  
0       0  
1       2  
2       2  
3       0  
4       0

In [35]:
new_data = np.array([[0.72,0.87,5,223,5,0,0,1,0]])
new_data = new_data.reshape(1,-1)

In [36]:
knn_final.predict((new_data))

array([1], dtype=int64)

In [37]:
knn_final.predict_proba(new_data)

array([[0., 1.]])